### ISSUE TITLE
Dates are returned as objects

### ISSUE THREAD

**Issue by archiewood** [evidence-dev/sqltools-bigquery-driver#1]
![image](https://github.com/evidence-dev/sqltools-bigquery-driver/assets/58074498/9029d8d7-234b-4512-9495-e3f6d6dd7160)

May need to handle these explicitly to unpack the objects

**Comment by archiewood** [comment]
Not fixed

**Comment by archiewood** [comment]
I believe this is now fixed.
@hughess let me know if you are still having the issue

**Comment by hughess** [comment]
@archiewood just tried it and it's working for me!
