### ISSUE TITLE
Disable autocomplete

### ISSUE THREAD

**Issue by prehani** [evidence-dev/sqltools-bigquery-driver#15]
I didn't see this in the docs--is there a straightforward way to disable keyword autocomplete? Or only begin after a character for that keyword is typed?

Thanks!

**Comment by archiewood** [comment]
You might have more luck over at the [main SQLTools repo](https://github.com/mtxr/vscode-sqltools/) - autocomplete is mainly managed by that extension

The database specific drivers just configure which keywords are exposed

**Comment by archiewood** [comment]
I believe you can configure this for SQLtools globally by removing sql from 

`sqltools.completionLanguages`


![CleanShot 2024-09-09 at 17 45 18@2x](https://github.com/user-attachments/assets/08d8d47e-dd7c-41c2-9359-3cd6dff6fe08)
