### ISSUE TITLE
Feature Request: Sort datasets in alphabetical order

### ISSUE THREAD

**Issue by vcolmenar** [evidence-dev/sqltools-bigquery-driver#21]
Description

A GCP project with several datasets aren't in alphabetical order.
By sorting them alphabetically, it will make locating datasets easier.

Acceptance Criteria

1. Datasets are auto sorted after expanding a GCP Project

P.S. Tool is awesome, thank you for making this available to the community!

Screenshot of unsorted datasets:
![image](https://github.com/evidence-dev/sqltools-bigquery-driver/assets/2059746/bbae1e15-15c2-4972-b3de-42abd9b57641)

**Comment by dmytro-lytvyn** [comment]
Added a PR to address this: https://github.com/evidence-dev/sqltools-bigquery-driver/pull/22

**Comment by archiewood** [comment]
Closed by #22
