### ISSUE TITLE
Wrong output with JSON function

### ISSUE THREAD

**Issue by cdevacc1** [evidence-dev/sqltools-bigquery-driver#25]
`SELECT JSON_KEYS(JSON '{"a": {"b":1}}', 1) AS json_keys`

The query above return Null.
It should return 'a'

**Comment by archiewood** [comment]
The problem here appears to be that ARRAY result types are not handled correctly: JSON_KEYS has a return type of `ARRAY<string>`

This can be reproduced by:

```sql
SELECT GENERATE_ARRAY(1, 5) AS example_array
```
